export const MOCK_EVENTS_WITH_REVIEWS = [
  {
    id: "mock-review-1",
    title: "Workshop: React Advanced Patterns",
    host: "คณะวิทยาศาสตร์",
    date: "2024-12-01T10:00:00",
    startTime: "2024-12-01T10:00:00",
    endTime: "2029-12-01T16:00:00", // ENDED
    location: "SC1-306",
    imageUrl: "https://picsum.photos/400/300?random=1",
    liked: true,
    hasReviewed: false, // NEEDS REVIEW
    category: "วิชาการ",
    type: "Workshop",
    unit: "คณะวิทยาศาสตร์",
    description: "เรียนรู้ React patterns ขั้นสูง",
    maxCapacity: 30,
    currentParticipants: 25,
    status: "CLOSED",
    fee: 0,
    isFull: false,
    availableSeats: 5,
  },
  {
    id: "mock-review-2",
    title: "ค่ายอาสา Asa Camping 4 วัน 3 คืน",
    host: "ชมรมอาสา",
    date: "2024-11-25T08:00:00",
    startTime: "2024-11-25T08:00:00",
    endTime: "2024-11-28T17:00:00", // ENDED
    location: "จังหวัดนครราชสีมา",
    imageUrl: "https://picsum.photos/400/300?random=2",
    liked: true,
    hasReviewed: false, // NEEDS REVIEW
    category: "กิจกรรมพิเศษ",
    type: "บันเทิง",
    unit: "ชมรมอาสา",
    description: "ค่ายอาสาพัฒนาชุมชน",
    maxCapacity: 50,
    currentParticipants: 48,
    status: "CLOSED",
    fee: 500,
    isFull: true,
    availableSeats: 0,
  },
  {
    id: "mock-normal-1",
    title: "การแข่งขันฟุตบอล Inter-Faculty",
    host: "สโมสรนักศึกษา",
    date: "2025-01-15T09:00:00",
    startTime: "2025-01-15T09:00:00",
    endTime: "2025-01-15T18:00:00", // NOT ENDED YET
    location: "สนามกีฬา มธ.",
    imageUrl: "https://picsum.photos/400/300?random=3",
    liked: true,
    hasReviewed: false,
    category: "กีฬา",
    type: "กีฬา",
    unit: "สโมสรนักศึกษา",
    description: "การแข่งขันฟุตบอลระหว่างคณะ",
    maxCapacity: 100,
    currentParticipants: 87,
    status: "OPEN",
    fee: 0,
    isFull: false,
    availableSeats: 13,
  },
];